Revert ""NoMethodError: undefined method `match?' for nil on https://e-komik.org/actor#main-key" の対応"
This reverts commit 0ab5b36bd8519bc3f4294a93146b8dfbad3aff76.